"""
The Richardson number (Ri = N²/S²) tells you about the potential for these shears to cause turbulent mixing:

	Ri<1/4 (or 0.25): This is the classical critical value for the Kelvin-Helmholtz instability in steady, 
	parallel shear flow. When the Richardson number drops below this value, the shear is strong enough to 
	overcome the stabilizing stratification, leading to shear instability and the rapid generation of turbulence and mixing.

	1/4<Ri<1: In this range, the flow is still theoretically stable to Kelvin-Helmholtz instability,
	 but it is often observed that turbulence, once initiated, can be sustained or intermittently generated up to Ri≈1.

	Ri>1: The stratification is strong enough relative to the shear that the flow is generally 
	stable and not prone to shear-induced turbulence.


NIWs are primarily generated by time-varying wind stress, which creates a strong, near-inertial 
shear in the upper ocean boundary layer.

	In this region, the strong shear associated with the NIWs can cause the local Richardson number to drop 
	to or below Ri<1/4.

	This low Ri indicates a turbulent transition, leading to the dissipation of the NIW energy locally, 
	which contributes significantly to upper-ocean mixing and deepens the mixed layer.

As NIWs propagate into the ocean interior, particularly in the coastal ocean where topography and background 
flows are important, the Richardson number diagnoses regions where their energy is dissipated


Shear Enhancement: When NIWs interact with mesoscale eddies (like anticyclones) or strong background currents 
(like coastal jets), their vertical shear can be locally amplified. This increase in S2 causes a reduction in Ri.

Wave Breaking and Mixing: When the local Richardson number drops below the critical threshold (Ri≤1/4), 
the amplified NIW shear becomes unstable, causing the wave to break and dissipate its energy into turbulent mixing. 
This process is a major pathway for transferring wind energy from the surface to the deep ocean interior and seafloor, 
affecting nutrient distribution and stratification in the coastal zone.

"""

time = tv_A.ocean_time

date_ranges_cf = [
	("2004-03-19", "2004-03-24"),
	("2004-04-09", "2004-04-11")
	
]

date_ranges_hurricane = [
	("2004-03-23", "2004-03-30")
	
]

fig = plt.figure(figsize=(15, 9))  #width, height
gs = gridspec.GridSpec(nrows=4, ncols=4, width_ratios=[1,1,1,1], height_ratios=[1,1,1,1])
gs.update(left=0.05, right=0.98, wspace=0.25, hspace=0.2, top=0.99, bottom=0.05)

##############----> Tau per time <-----############

bar_title = r'N m$^{-2}$'
#--->A
ax_ta = plt.subplot(gs[0, 0])
ax_ta.plot(time, tau_A, zorder=2,color='k',label=r'$\tau$ (N m$^{-2}$)')  
ax_ta.text(0.02, 0.95, '(a)', transform=ax_ta.transAxes, fontsize=8, fontweight='bold')

for start, end in date_ranges_cf:
	ax_ta.axvspan(pd.to_datetime(start), pd.to_datetime(end),
				color='purple', alpha=0.2, zorder=1, label="_nolegend_")
ax_ta.axvspan(pd.to_datetime(date_ranges_cf[0][0]), pd.to_datetime(date_ranges_cf[0][1]),
			color='purple', alpha=0.2, zorder=1, label='Cold Fronts')

ax_ta.legend(loc='best')
ax_ta.tick_params(axis='y', labelsize='x-small')
ax_ta.xaxis.set_major_locator(mdates.DayLocator(interval=5))
ax_ta.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
plt.setp(ax_ta.get_xticklabels(), rotation=15, ha='center', fontsize='x-small')
ax_ta.grid(True, which='major', alpha=0.3, linewidth=0.6)
ax_ta.grid(True, which='minor', alpha=0.15, linewidth=0.5)
ax_ta.minorticks_on()
for spine in ['top', 'right']:
	ax_ta.spines[spine].set_visible(False)
ax_ta.set_ylabel(bar_title, fontsize='small')  # (same units as colorbar)
ax_ta.set_ylim(bottom=0, top=0.4)
#--->B
ax_tb = plt.subplot(gs[0, 1])
ax_tb.plot(time, tau_B, zorder=2,color='blue',label=r'$\tau$ (N m$^{-2}$)')  
ax_tb.text(0.02, 0.95, '(b)', transform=ax_tb.transAxes, fontsize=8, fontweight='bold')

for start, end in date_ranges_cf:
	ax_tb.axvspan(pd.to_datetime(start), pd.to_datetime(end),
				color='purple', alpha=0.2, zorder=1, label="_nolegend_")
ax_tb.axvspan(pd.to_datetime(date_ranges_cf[0][0]), pd.to_datetime(date_ranges_cf[0][1]),
			color='purple', alpha=0.2, zorder=1, label='Cold Fronts')

ax_tb.tick_params(axis='y', labelsize='x-small')
ax_tb.xaxis.set_major_locator(mdates.DayLocator(interval=5))
ax_tb.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
plt.setp(ax_tb.get_xticklabels(), rotation=15, ha='center', fontsize='x-small')
ax_tb.grid(True, which='major', alpha=0.3, linewidth=0.6)
ax_tb.grid(True, which='minor', alpha=0.15, linewidth=0.5)
ax_tb.minorticks_on()
for spine in ['top', 'right']:
	ax_tb.spines[spine].set_visible(False)
ax_tb.set_ylabel(None, fontsize='small')  # (same units as colorbar)
ax_tb.set_ylim(bottom=0, top=0.4)


#--->C
ax_tc = plt.subplot(gs[0, 2])
ax_tc.plot(time, tau_C, zorder=2,color='orange',label=r'$\tau$ (N m$^{-2}$)')  
ax_tc.text(0.02, 0.95, '(c)', transform=ax_tc.transAxes, fontsize=8, fontweight='bold')

for start, end in date_ranges_cf:
	ax_tc.axvspan(pd.to_datetime(start), pd.to_datetime(end),
				color='purple', alpha=0.2, zorder=1, label="_nolegend_")
ax_tc.axvspan(pd.to_datetime(date_ranges_cf[0][0]), pd.to_datetime(date_ranges_cf[0][1]),
			color='purple', alpha=0.2, zorder=1, label='Cold Fronts')

ax_tc.tick_params(axis='y', labelsize='x-small')
ax_tc.xaxis.set_major_locator(mdates.DayLocator(interval=5))
ax_tc.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
plt.setp(ax_tc.get_xticklabels(), rotation=15, ha='center', fontsize='x-small')
ax_tc.grid(True, which='major', alpha=0.3, linewidth=0.6)
ax_tc.grid(True, which='minor', alpha=0.15, linewidth=0.5)
ax_tc.minorticks_on()
for spine in ['top', 'right']:
	ax_tc.spines[spine].set_visible(False)
ax_tc.set_ylabel(None, fontsize='small')  # (same units as colorbar)
ax_tc.set_ylim(bottom=0, top=0.4)

#--->D
ax_td = plt.subplot(gs[0, 3])
ax_td.plot(time, tau_D, zorder=2,color='red',label=r'$\tau$ (N m$^{-2}$)')  
ax_td.text(0.02, 0.95, '(d)', transform=ax_td.transAxes, fontsize=8, fontweight='bold')

for start, end in date_ranges_cf:
	ax_td.axvspan(pd.to_datetime(start), pd.to_datetime(end),
				color='purple', alpha=0.2, zorder=1, label="_nolegend_")
ax_td.axvspan(pd.to_datetime(date_ranges_cf[0][0]), pd.to_datetime(date_ranges_cf[0][1]),
			color='purple', alpha=0.2, zorder=1, label='Cold Fronts')

ax_td.tick_params(axis='y', labelsize='x-small')
ax_td.xaxis.set_major_locator(mdates.DayLocator(interval=5))
ax_td.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
plt.setp(ax_td.get_xticklabels(), rotation=15, ha='center', fontsize='x-small')
ax_td.grid(True, which='major', alpha=0.3, linewidth=0.6)
ax_td.grid(True, which='minor', alpha=0.15, linewidth=0.5)
ax_td.minorticks_on()
for spine in ['top', 'right']:
	ax_td.spines[spine].set_visible(False)
ax_td.set_ylabel(None, fontsize='small')  # (same units as colorbar)
ax_td.set_ylim(bottom=0, top=0.4)

##############----> N2 per time <-----############

#------> N2 colorbar
cmap_N = plt.cm.cubehelix_r
vmin_N = 0
vmax_N = 1
norm_N = mpl.colors.Normalize(vmin=vmin_N, vmax=vmax_N)
levels = np.linspace(15,19, 4)

####---> A
a_N2 = plt.subplot(gs[1, 0])
a_N2.text(0.02, 0.05, '(e)', transform=a_N2.transAxes, fontsize=8, fontweight='bold')
a_N2.set_ylim(-150, 0) 
a_N2.contourf(time, zcross_A, shear_A_plot[:,1:].T*1e2, cmap=cmap_N, levels=50,norm=norm_N)
a_N2.plot(time,ml_A*-1,c='grey',lw=1.2,zorder=4)
a_N2.set_xlabel(None,size='x-small')
a_N2.set_ylabel('m',size='small')
a_N2.tick_params(axis='both', labelsize='x-small')
a_N2.tick_params(axis='x', labelsize='x-small', rotation=25)
a_N2.tick_params(axis='y', labelsize='x-small')
a_N2.xaxis.set_major_locator(mdates.DayLocator(interval=5))
a_N2.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
a_N2.fill_between(time, 0, ml_A*-1, color='white', zorder=3)
####---> B
b_N2 = plt.subplot(gs[1, 1])
b_N2.text(0.02, 0.05, '(f)', transform=b_N2.transAxes, fontsize=8, fontweight='bold')
b_N2.set_ylim(-150, 0) 
b_N2.contourf(time, zcross_B, shear_B_plot[:,1:].T*1e2, cmap=cmap_N, levels=50,norm=norm_N)
b_N2.plot(time,ml_B*-1,c='grey',lw=1.2,zorder=4)
b_N2.set_xlabel(None,size='x-small')
b_N2.set_ylabel(None)
b_N2.tick_params(axis='both', labelsize='x-small')
b_N2.tick_params(axis='x', labelsize='x-small', rotation=25)
b_N2.tick_params(axis='y', labelsize='x-small')
b_N2.xaxis.set_major_locator(mdates.DayLocator(interval=5))
b_N2.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
b_N2.fill_between(time, 0, ml_B*-1, color='white', zorder=3)


# Colorbar
cbar_1 = inset_axes(b_N2, width="60%", height="3%", loc=2)
cbar_1.set_facecolor('lightgray')
cb1 = mpl.colorbar.ColorbarBase(cbar_1, cmap=cmap_N, norm=norm_N, extend='max', orientation='horizontal')
cb1.set_label(r'$S \times 10^{-2}$ s$^{-1}$', size='small')
cbar_1.xaxis.set_ticks_position('bottom')
cbar_1.tick_params(axis='x', labelsize='x-small', rotation=25)

####---> C
c_N2 = plt.subplot(gs[1, 2])
c_N2.text(0.02, 0.05, '(g)', transform=c_N2.transAxes, fontsize=8, fontweight='bold')
c_N2.set_ylim(-150, 0) 
c_N2.contourf(time, zcross_C, shear_C_plot[:,1:].T*1e2, cmap=cmap_N, levels=50,norm=norm_N)
c_N2.plot(time,ml_C*-1,c='grey',lw=1.2,zorder=4)
c_N2.set_xlabel(None,size='x-small')
c_N2.set_ylabel(None)
c_N2.tick_params(axis='both', labelsize='x-small')
c_N2.tick_params(axis='x', labelsize='x-small', rotation=25)
c_N2.tick_params(axis='y', labelsize='x-small')
c_N2.xaxis.set_major_locator(mdates.DayLocator(interval=5))
c_N2.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
c_N2.fill_between(time, 0, ml_C*-1, color='white', zorder=3)
####---> D
d_N2 = plt.subplot(gs[1, 3])
d_N2.text(0.02, 0.05, '(h)', transform=d_N2.transAxes, fontsize=8, fontweight='bold')
d_N2.set_ylim(-150, 0) 
d_N2.contourf(time, zcross_D, shear_D_plot[:,1:].T*1e2, cmap=cmap_N, levels=50,norm=norm_N)
d_N2.plot(time,ml_D*-1,c='grey',lw=1.2,zorder=4)
d_N2.set_xlabel(None,size='x-small')
d_N2.set_ylabel(None)
d_N2.tick_params(axis='both', labelsize='x-small')
d_N2.tick_params(axis='x', labelsize='x-small', rotation=25)
d_N2.tick_params(axis='y', labelsize='x-small')
d_N2.xaxis.set_major_locator(mdates.DayLocator(interval=5))
d_N2.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
d_N2.fill_between(time, 0, ml_D*-1, color='white', zorder=3)

##############----> ri per time <-----############

#------> ri colorbar
cmap_N = plt.cm.Paired
vmin_N = 0
vmax_N = 4
norm_N = mpl.colors.Normalize(vmin=vmin_N, vmax=vmax_N)
levels = np.linspace(15,19, 4)

####---> A
a_ri = plt.subplot(gs[2, 0])
a_ri.text(0.02, 0.05, '(i)', transform=a_ri.transAxes, fontsize=8, fontweight='bold')
a_ri.set_ylim(-150, 0) 
a_ri.contourf(time, zcross_A, 1/ri_A_plot.T, cmap=cmap_N, levels=50,norm=norm_N)
a_ri.plot(time,ml_A*-1,c='grey',lw=1.2,zorder=4)
a_ri.set_xlabel(None,size='x-small')
a_ri.set_ylabel('m',size='small')
a_ri.tick_params(axis='both', labelsize='x-small')
a_ri.tick_params(axis='x', labelsize='x-small', rotation=25)
a_ri.tick_params(axis='y', labelsize='x-small')
a_ri.xaxis.set_major_locator(mdates.DayLocator(interval=5))
a_ri.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
#a_ri.fill_between(time, 0, ml_A*-1, color='white', zorder=3)
####---> B
b_ri = plt.subplot(gs[2, 1])
b_ri.text(0.02, 0.05, '(j)', transform=b_ri.transAxes, fontsize=8, fontweight='bold')
b_ri.set_ylim(-150, 0) 
b_ri.contourf(time, zcross_B, 1/ri_B_plot.T, cmap=cmap_N, levels=50,norm=norm_N)
b_ri.plot(time,ml_B*-1,c='grey',lw=1.2,zorder=4)
b_ri.set_xlabel(None,size='x-small')
b_ri.set_ylabel(None)
b_ri.tick_params(axis='both', labelsize='x-small')
b_ri.tick_params(axis='x', labelsize='x-small', rotation=25)
b_ri.tick_params(axis='y', labelsize='x-small')
b_ri.xaxis.set_major_locator(mdates.DayLocator(interval=5))
b_ri.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
#b_ri.fill_between(time, 0, ml_B*-1, color='white', zorder=3)

cbar_2 = inset_axes(
	b_ri, 
	width="60%", 
	height="10%", 
	loc=3, 
	bbox_to_anchor=[0.05, 0.2, 0.7, 0.4],
	bbox_transform=b_ri.transAxes
)

cbar_2.set_facecolor('lightgray')
cb2 = mpl.colorbar.ColorbarBase(cbar_2, cmap=cmap_N, norm=norm_N, extend='max', orientation='horizontal')
cb2.set_label(r'$Ri^{-1}$ s$^{2}$', size='small')
cbar_2.xaxis.set_ticks_position('bottom')
cbar_2.tick_params(axis='x', labelsize='x-small', rotation=25)

####---> C
c_ri = plt.subplot(gs[2, 2])
c_ri.text(0.02, 0.05, '(k)', transform=c_ri.transAxes, fontsize=8, fontweight='bold')
c_ri.set_ylim(-150, 0) 
c_ri.contourf(time, zcross_C, 1/ri_C_plot.T, cmap=cmap_N, levels=50,norm=norm_N)
c_ri.plot(time,ml_C*-1,c='grey',lw=1.2,zorder=4)
c_ri.set_xlabel(None,size='x-small')
c_ri.set_ylabel(None)
c_ri.tick_params(axis='both', labelsize='x-small')
c_ri.tick_params(axis='x', labelsize='x-small', rotation=25)
c_ri.tick_params(axis='y', labelsize='x-small')
c_ri.xaxis.set_major_locator(mdates.DayLocator(interval=5))
c_ri.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
#c_ri.fill_between(time, 0, ml_C*-1, color='white', zorder=3)
####---> D
d_ri = plt.subplot(gs[2, 3])
d_ri.text(0.02, 0.05, '(l)', transform=d_ri.transAxes, fontsize=8, fontweight='bold')
d_ri.set_ylim(-150, 0) 
d_ri.contourf(time, zcross_D, 1/ri_D_plot.T, cmap=cmap_N, levels=50,norm=norm_N)
d_ri.plot(time,ml_D*-1,c='grey',lw=1.2,zorder=4)
d_ri.set_xlabel(None,size='x-small')
d_ri.set_ylabel(None)
d_ri.tick_params(axis='both', labelsize='x-small')
d_ri.tick_params(axis='x', labelsize='x-small', rotation=25)
d_ri.tick_params(axis='y', labelsize='x-small')
d_ri.xaxis.set_major_locator(mdates.DayLocator(interval=5))
d_ri.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
#d_ri.fill_between(time, 0, ml_D*-1, color='white', zorder=3)

#########-----> Tendency Horizontal KE <-----####

bar_title=r'$\frac{d \mathrm{KE}^{\prime}}{dt} \vert_{\mathrm{mld}}$ ($\mathrm{mJ}\,\mathrm{h}^{-1}$)'
#--->A
kt_a = plt.subplot(gs[3, 0])
kt_a.plot(time, eke_t_A_at_MLD*1000, zorder=2,color='k',label=bar_title)  
kt_a.text(0.02, 0.95, '(m)', transform=kt_a.transAxes, fontsize=8, fontweight='bold')

for start, end in date_ranges_cf:
	kt_a.axvspan(pd.to_datetime(start), pd.to_datetime(end),
				color='purple', alpha=0.2, zorder=1, label="_nolegend_")
kt_a.axvspan(pd.to_datetime(date_ranges_cf[0][0]), pd.to_datetime(date_ranges_cf[0][1]),
			color='purple', alpha=0.2, zorder=1, label='Cold Fronts')

kt_a.legend(loc='best')
kt_a.tick_params(axis='y', labelsize='x-small')
kt_a.xaxis.set_major_locator(mdates.DayLocator(interval=5))
kt_a.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
plt.setp(kt_a.get_xticklabels(), rotation=15, ha='center', fontsize='x-small')
kt_a.grid(True, which='major', alpha=0.3, linewidth=0.6)
kt_a.grid(True, which='minor', alpha=0.15, linewidth=0.5)
kt_a.minorticks_on()
for spine in ['top', 'right']:
	kt_a.spines[spine].set_visible(False)
kt_a.set_ylabel(bar_title, fontsize='small')
kt_a.set_ylim(bottom=-6, top=6)


#--->B
kt_b = plt.subplot(gs[3, 1])
kt_b.plot(time, eke_t_B_Bt_MLD*1000, zorder=2,color='blue',label=r'mJ h$^{-1}$')  
kt_b.text(0.02, 0.95, '(n)', transform=kt_b.transAxes, fontsize=8, fontweight='bold')

for start, end in date_ranges_cf:
	kt_b.axvspan(pd.to_datetime(start), pd.to_datetime(end),
				color='purple', alpha=0.2, zorder=1, label="_nolegend_")
kt_b.axvspan(pd.to_datetime(date_ranges_cf[0][0]), pd.to_datetime(date_ranges_cf[0][1]),
			color='purple', alpha=0.2, zorder=1, label='Cold Fronts')

kt_b.tick_params(axis='y', labelsize='x-small')
kt_b.xaxis.set_major_locator(mdates.DayLocator(interval=5))
kt_b.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
plt.setp(kt_b.get_xticklabels(), rotation=15, ha='center', fontsize='x-small')
kt_b.grid(True, which='major', alpha=0.3, linewidth=0.6)
kt_b.grid(True, which='minor', alpha=0.15, linewidth=0.5)
kt_b.minorticks_on()
for spine in ['top', 'right']:
	kt_b.spines[spine].set_visible(False)
kt_b.set_ylabel(None, fontsize='small')
kt_b.set_ylim(bottom=-6, top=6)

#--->C
kt_c = plt.subplot(gs[3, 2])
kt_c.plot(time, eke_t_C_Ct_MLD*1000, zorder=2,color='orange',label=r'mJ h$^{-1}$')  
kt_c.text(0.02, 0.95, '(o)', transform=kt_c.transAxes, fontsize=8, fontweight='bold')

for start, end in date_ranges_cf:
	kt_c.axvspan(pd.to_datetime(start), pd.to_datetime(end),
				color='purple', alpha=0.2, zorder=1, label="_nolegend_")
kt_c.axvspan(pd.to_datetime(date_ranges_cf[0][0]), pd.to_datetime(date_ranges_cf[0][1]),
			color='purple', alpha=0.2, zorder=1, label='Cold Fronts')

kt_c.tick_params(axis='y', labelsize='x-small')
kt_c.xaxis.set_major_locator(mdates.DayLocator(interval=5))
kt_c.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
plt.setp(kt_c.get_xticklabels(), rotation=15, ha='center', fontsize='x-small')
kt_c.grid(True, which='major', alpha=0.3, linewidth=0.6)
kt_c.grid(True, which='minor', alpha=0.15, linewidth=0.5)
kt_c.minorticks_on()
for spine in ['top', 'right']:
	kt_c.spines[spine].set_visible(False)
kt_c.set_ylabel(None, fontsize='small')
kt_c.set_ylim(bottom=-6, top=6)
#--->D
kt_d = plt.subplot(gs[3, 3])
kt_d.plot(time, eke_t_D_Dt_MLD*1000, zorder=2,color='red',label=r'mJ h$^{-1}$')  
kt_d.text(0.02, 0.95, '(p)', transform=kt_d.transAxes, fontsize=8, fontweight='bold')

for start, end in date_ranges_cf:
	kt_d.axvspan(pd.to_datetime(start), pd.to_datetime(end),
				color='purple', alpha=0.2, zorder=1, label="_nolegend_")
kt_d.axvspan(pd.to_datetime(date_ranges_cf[0][0]), pd.to_datetime(date_ranges_cf[0][1]),
			color='purple', alpha=0.2, zorder=1, label='Cold Fronts')

for start, end in date_ranges_hurricane:
	kt_d.axvspan(pd.to_datetime(start), pd.to_datetime(end),
				color='purple', alpha=0.2, zorder=1, label="_nolegend_")
kt_d.axvspan(pd.to_datetime(date_ranges_hurricane[0][0]), pd.to_datetime(date_ranges_hurricane[0][1]),
			color='cyan', alpha=0.2, zorder=1, label='Catarina Hurricane')

kt_d.tick_params(axis='y', labelsize='x-small')
kt_d.xaxis.set_major_locator(mdates.DayLocator(interval=5))
kt_d.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
plt.setp(kt_d.get_xticklabels(), rotation=15, ha='center', fontsize='x-small')
kt_d.grid(True, which='major', alpha=0.3, linewidth=0.6)
kt_d.grid(True, which='minor', alpha=0.15, linewidth=0.5)
kt_d.minorticks_on()
for spine in ['top', 'right']:
	kt_d.spines[spine].set_visible(False)
kt_d.set_ylabel(None, fontsize='small')
kt_d.set_ylim(bottom=-6, top=6)

plt.savefig('fig_3_tau_shear_ke_v2.png')